# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'collectionViewStudy' do
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'collectionViewStudyTests' do
    inherit! :search_paths
  end

  target 'collectionViewStudyUITests' do
    # Pods for testing
  end

end
